version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  apt_packages:
    - graphviz

  jobs:
    pre_build:
      # This -e flag is incredibly important. Without it, the package won't install properly. No, I don't know why
      - $(pwd | sed "s/checkouts\(\/[^/]\+\)\$/envs\1/")/bin/python -m pip install -e '.[docs]'
      - . $(pwd | sed "s/checkouts\(\/[^/]\+\)\$/envs\1/")/bin/activate; cd docs; make precompile


sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true

python:
  system_packages: false
